name: Send Email on New Issue

on:
  issues:
    types: [opened]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.strato.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "Er is een nieuw issue gecreerd op Github: ${{ github.event.issue.title }}"
        body: |
          Er is een nieuw issue gecreeerd op Github. Maak een nieuwe ticket aan en koppel deze aan dit issue voor verdere communicatie

          Title: ${{ github.event.issue.title }}
          Body: ${{ github.event.issue.body }}
          Issue URL: ${{ github.event.issue.html_url }}
        to: aedes_sandbox@devick.com
        from: patrick@devick.com
        cc: p.devick@aedes.nl
        convert_markdown: true
