name: Send Email on New Issue

on:
  issues:
    types: [opened]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.strato.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "New Issue Created: ${{ github.event.issue.title }}"
        body: |
          A new issue has been created in the repository.

          Title: ${{ github.event.issue.title }}
          Body: ${{ github.event.issue.body }}
          Issue URL: ${{ github.event.issue.html_url }}
        to: aedes_sandbox@devick.com
        from: patrick@devick.com
